version: '3.8'

services:
  app:
    build:
      context: .
      target: build
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  test:
    build:
      context: .
      target: test
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm test
